- hosts:  #your host file name or dynamic tag/group value in case of dynamic inventory
  become: yes

  vars:
    consul_mode: "agent"
    consul_dir: #location of your consul installation
    consul_data_dir:  "{{ consul_dir }}/data"
    consul_conf_dir:  "{{ consul_dir }}/conf"
    consul_conf_datacenter: #datacenter name of your choice
    consul_conf_bootstrap_expect: #number of instance of consul you want to run in server mode.
    consul_domain: #custom dns name of using consul dns
    consul_conf_bind_addr: 0.0.0.0
    consul_conf_client_addr: 0.0.0.0
    consul_agent: yes
    consul_server: no

  roles:
    - role: ansible-consul
